name: Second workflow in the chain

on:
  workflow_run:
    workflows: First workflow in the chain
    types: completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - run: echo Updated second
